# Generated by Django 5.0 on 2024-01-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content', models.TextField(blank=True, max_length=140, null=True)),
                ('zairyou', models.TextField(blank=True, max_length=392, null=True)),
                ('tukurikata', models.TextField(blank=True, max_length=1000, null=True)),
                ('sankou', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
