# Generated by Django 5.0 on 2024-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_place',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_recipe',
            field=models.ManyToManyField(blank=True, to='app.recipe', verbose_name='お気に入りの場所'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
